name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Apply Terraform
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1

    - name: Update And install gnupg
      run: sudo apt-get update && sudo apt-get install -y gnupg software-properties-common 
  
    - name: Download Keyring
      run: wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null

    - name: Command gpg
      run: gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
      
    - name: Create Source list
      run: echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list

    - name: Update Repo
      run: sudo apt update -y

    - name: Update Repo
      run: sudo apt-get install terraform -y

    - name: Test Diretorio
      run: pwd && ls -la && whereis terraform && ls -lha /usr/bin/ && sudo apt-get install tree -y && tree /home/runner/work/env_start2finish

    - name: Terraform Init
      run: /usr/bin/terraform init
      working-directory: /home/runner/work/env_start2finish/env_start2finish

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: /home/runner/work/env_start2finish/env_start2finish

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy files via SCP
      run: scp -r ./webpage ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/var/www/html
